version: "2.4"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    restart: on-failure
    mem_limit: 1g
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data
    networks:
      - local
    depends_on:
      - fluent-bit
    logging:
      driver: fluentd
      options:
        tag: fyp.es
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.10.2
    restart: on-failure
    mem_limit: 256m
    environment:
      - ELASTICSEARCH_URL="http://elasticsearch:9200"
    ports:
      - 5601:5601
    networks:
      - local
    depends_on:
      - fluent-bit
      - elasticsearch
    logging:
      driver: fluentd
      options:
        tag: fyp.kibana
  fluent-bit:
    image: fluent/fluent-bit:1.8
    command:
      - /fluent-bit/bin/fluent-bit
      - --config=/etc/fluent-bit/fluent-bit.conf
    environment:
      - FLB_ES_HOST=elasticsearch
      - FLB_ES_PORT=9200
    ports:
      - 24224:24224
    volumes:
      - ./config/:/etc/fluent-bit/:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log/nginx:/var/log/nginx:ro
      - /var/log/fail2ban.log:/var/log/fail2ban.log:ro
      - /var/log/auth.log:/var/log/auth.log:ro
      - /var/log/suricata:/var/log/suricata:ro  
    networks:
      - local
    logging:
      driver: fluentd
      options:
        tag: fyp.fluent-bit

networks:
  local:
    driver: bridge

